ENV["AWS_ACCESS_KEY_ID"] = 'AKIAJTHDTGA4IP5A7L6Q'
ENV["AWS_SECRET_ACCESS_KEY"] = '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'
ENV["AWS_S3_BUCKET"] = 'gumballer'


# TODO THIS MUSNT BE ON HEROKU ignored anyway but fyi
require 'openssl'
OpenSSL::SSL::VERIFY_PEER = OpenSSL::SSL::VERIFY_NONE
